version: 2.1

jobs:
  check_syntax:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - run: 
          name: "create venv"
          command: |
            python3 -m venv ~/.devops
      - run:
          name: "Install dependencies"
          command: |
            make install
      - run:
          name: "Check syntaxt code"
          command: |
            make lint
  build_image:
    working_directory: app/
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: echo dir
          command: |
            ls -la
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build docker iamge
          command: |
            cd ~/app
            docker build -t app .
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      - run:
          name: push image to docker hub
          command: |
            cd ~/app
            docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
            docker tag app "daoducnha29493/udacity-devops-final:${CIRCLE_SHA1}"
            docker push "daoducnha29493/udacity-devops-final:${CIRCLE_SHA1}"

workflows:
  default:
    jobs:
      - check_syntax
      - build_image:
          requires: [check_syntax]


